export interface StateData {
  id: string;
  name: string;
  abbreviation: string;
  capital: string;
  capitalPop: string;
  unionOrder: number;
  unionDate: string;
  region: string;
  areaSqMiles: string;
  pronunciation: string;
  funFacts: string[];
  stateBird: string;
  stateFlower: string;
  stateMotto: string;
  fipsCode: string;   // FIPS numeric code as string, e.g. "01"
  centerLon: number;  // geographic center longitude
  centerLat: number;  // geographic center latitude
  difficulty: 1 | 2 | 3 | 4 | 5; // 1=easiest, 5=hardest
}

// Difficulty assignments:
// 1 - Iconic states everyone knows (CA, TX, FL, NY, AK, HI)
// 2 - Large/well-known states (PA, IL, OH, GA, MI, WA, CO, AZ, VA, NC)
// 3 - Mid-recognition states (OR, NV, LA, TN, MN, WI, MO, MA, NJ, MD, SC, AL, KY, OK, IN)
// 4 - Harder states (AR, KS, NE, IA, MS, NM, UT, CT, ME, MT, WV, ID)
// 5 - Most confusing states (ND, SD, WY, VT, NH, RI, DE)

export const STATES: StateData[] = [
  {
    id: "alabama",
    name: "Alabama",
    abbreviation: "AL",
    capital: "Montgomery",
    capitalPop: "~200,000",
    unionOrder: 22,
    unionDate: "December 14, 1819",
    region: "Southeast",
    areaSqMiles: "52,420 sq mi",
    pronunciation: "al-uh-BAM-uh",
    funFacts: [
      "Alabama is known as the 'Heart of Dixie' and has more than 67 species of oak trees.",
      "The first electric trolley system in the US was built in Montgomery, Alabama in 1886.",
      "Alabama has the most freshwater fish species diversity of any state east of the Mississippi River.",
    ],
    stateBird: "Yellowhammer (Northern Flicker)",
    stateFlower: "Camellia",
    stateMotto: "Audemus jura nostra defendere (We dare defend our rights)",
    fipsCode: "01",
    centerLon: -86.8,
    centerLat: 32.8,
    difficulty: 3,
  },
  {
    id: "alaska",
    name: "Alaska",
    abbreviation: "AK",
    capital: "Juneau",
    capitalPop: "~32,000",
    unionOrder: 49,
    unionDate: "January 3, 1959",
    region: "Pacific",
    areaSqMiles: "663,268 sq mi",
    pronunciation: "uh-LAS-kuh",
    funFacts: [
      "Alaska is the largest US state by area — bigger than the next three largest states combined.",
      "Alaska has more coastline than all other US states combined — over 33,000 miles.",
      "The Northern Lights (Aurora Borealis) can be seen in Alaska up to 243 days per year.",
    ],
    stateBird: "Willow Ptarmigan",
    stateFlower: "Forget-Me-Not",
    stateMotto: "North to the Future",
    fipsCode: "02",
    centerLon: -153.4,
    centerLat: 64.2,
    difficulty: 1,
  },
  {
    id: "arizona",
    name: "Arizona",
    abbreviation: "AZ",
    capital: "Phoenix",
    capitalPop: "~1,600,000",
    unionOrder: 48,
    unionDate: "February 14, 1912",
    region: "Southwest",
    areaSqMiles: "113,990 sq mi",
    pronunciation: "air-ih-ZOH-nuh",
    funFacts: [
      "Arizona's Grand Canyon is one of the Seven Natural Wonders of the World, stretching 277 miles long.",
      "Arizona is home to the largest Ponderosa Pine forest in North America.",
      "The saguaro cactus, Arizona's state flower, can live up to 200 years and weigh several tons.",
    ],
    stateBird: "Cactus Wren",
    stateFlower: "Saguaro Cactus Blossom",
    stateMotto: "Ditat Deus (God Enriches)",
    fipsCode: "04",
    centerLon: -111.1,
    centerLat: 34.3,
    difficulty: 2,
  },
  {
    id: "arkansas",
    name: "Arkansas",
    abbreviation: "AR",
    capital: "Little Rock",
    capitalPop: "~202,000",
    unionOrder: 25,
    unionDate: "June 15, 1836",
    region: "South",
    areaSqMiles: "53,179 sq mi",
    pronunciation: "AR-kan-saw",
    funFacts: [
      "Arkansas is the only US state where diamonds are mined commercially — visitors can dig for them at Crater of Diamonds State Park.",
      "The state is called the 'Natural State' due to its stunning natural scenery and outdoor beauty.",
      "Arkansas produces more than 50% of all rice grown in the United States.",
    ],
    stateBird: "Mockingbird",
    stateFlower: "Apple Blossom",
    stateMotto: "Regnat Populus (The People Rule)",
    fipsCode: "05",
    centerLon: -92.2,
    centerLat: 34.8,
    difficulty: 4,
  },
  {
    id: "california",
    name: "California",
    abbreviation: "CA",
    capital: "Sacramento",
    capitalPop: "~524,000",
    unionOrder: 31,
    unionDate: "September 9, 1850",
    region: "Pacific",
    areaSqMiles: "163,696 sq mi",
    pronunciation: "kal-ih-FOR-nyuh",
    funFacts: [
      "California has the largest economy of any US state — if it were a country, it would be the 5th largest economy in the world.",
      "The tallest trees on Earth, the coastal redwoods, grow in California and can reach over 380 feet tall.",
      "California produces more than a third of all vegetables and two-thirds of all fruits and nuts grown in the US.",
    ],
    stateBird: "California Quail",
    stateFlower: "California Poppy",
    stateMotto: "Eureka (I have found it)",
    fipsCode: "06",
    centerLon: -119.5,
    centerLat: 37.2,
    difficulty: 1,
  },
  {
    id: "colorado",
    name: "Colorado",
    abbreviation: "CO",
    capital: "Denver",
    capitalPop: "~715,000",
    unionOrder: 38,
    unionDate: "August 1, 1876",
    region: "Mountain West",
    areaSqMiles: "104,094 sq mi",
    pronunciation: "kol-uh-RAD-oh",
    funFacts: [
      "Colorado has 58 mountain peaks that are higher than 14,000 feet — nicknamed 'fourteeners.'",
      "Denver is nicknamed the 'Mile High City' because it sits at exactly 5,280 feet above sea level.",
      "Colorado is home to the world's largest flat-top mountain, Grand Mesa, covering 500 square miles.",
    ],
    stateBird: "Lark Bunting",
    stateFlower: "Rocky Mountain Columbine",
    stateMotto: "Nil Sine Numine (Nothing Without Providence)",
    fipsCode: "08",
    centerLon: -105.5,
    centerLat: 39.0,
    difficulty: 2,
  },
  {
    id: "connecticut",
    name: "Connecticut",
    abbreviation: "CT",
    capital: "Hartford",
    capitalPop: "~121,000",
    unionOrder: 5,
    unionDate: "January 9, 1788",
    region: "Northeast",
    areaSqMiles: "5,543 sq mi",
    pronunciation: "kuh-NET-ih-cut",
    funFacts: [
      "Connecticut was the first US state to have a law library, established in 1789.",
      "The lollipop was invented in New Haven, Connecticut, in 1908 at the Bradley Smith Company.",
      "Connecticut is home to Yale University, founded in 1701 — one of the oldest universities in the US.",
    ],
    stateBird: "American Robin",
    stateFlower: "Mountain Laurel",
    stateMotto: "Qui Transtulit Sustinet (He Who Transplanted Still Sustains)",
    fipsCode: "09",
    centerLon: -72.7,
    centerLat: 41.6,
    difficulty: 4,
  },
  {
    id: "delaware",
    name: "Delaware",
    abbreviation: "DE",
    capital: "Dover",
    capitalPop: "~38,000",
    unionOrder: 1,
    unionDate: "December 7, 1787",
    region: "Northeast",
    areaSqMiles: "2,489 sq mi",
    pronunciation: "DEL-uh-wair",
    funFacts: [
      "Delaware was the very first state to ratify the US Constitution, earning the nickname 'The First State.'",
      "More than half of all US publicly-traded companies are incorporated in Delaware due to its business-friendly laws.",
      "Delaware is the second smallest state in the US by area.",
    ],
    stateBird: "Blue Hen Chicken",
    stateFlower: "Peach Blossom",
    stateMotto: "Liberty and Independence",
    fipsCode: "10",
    centerLon: -75.5,
    centerLat: 38.9,
    difficulty: 5,
  },
  {
    id: "florida",
    name: "Florida",
    abbreviation: "FL",
    capital: "Tallahassee",
    capitalPop: "~199,000",
    unionOrder: 27,
    unionDate: "March 3, 1845",
    region: "Southeast",
    areaSqMiles: "65,758 sq mi",
    pronunciation: "FLOR-ih-duh",
    funFacts: [
      "Florida is home to the world's first commercial airline route, inaugurated in 1914 between St. Petersburg and Tampa.",
      "Florida has the longest coastline of any state in the continental US — over 1,350 miles.",
      "More than 1,000 native plant species can be found in the Florida Everglades, the largest subtropical wilderness in the US.",
    ],
    stateBird: "Mockingbird",
    stateFlower: "Orange Blossom",
    stateMotto: "In God We Trust",
    fipsCode: "12",
    centerLon: -81.5,
    centerLat: 28.5,
    difficulty: 1,
  },
  {
    id: "georgia",
    name: "Georgia",
    abbreviation: "GA",
    capital: "Atlanta",
    capitalPop: "~498,000",
    unionOrder: 4,
    unionDate: "January 2, 1788",
    region: "Southeast",
    areaSqMiles: "59,425 sq mi",
    pronunciation: "JOR-juh",
    funFacts: [
      "Georgia is the largest state east of the Mississippi River.",
      "Georgia produces more peanuts than any other state — about 42% of the US total.",
      "The Okefenokee Swamp, one of the world's largest intact freshwater ecosystems, is located in southern Georgia.",
    ],
    stateBird: "Brown Thrasher",
    stateFlower: "Cherokee Rose",
    stateMotto: "Wisdom, Justice, and Moderation",
    fipsCode: "13",
    centerLon: -83.4,
    centerLat: 32.7,
    difficulty: 1,
  },
  {
    id: "hawaii",
    name: "Hawaii",
    abbreviation: "HI",
    capital: "Honolulu",
    capitalPop: "~350,000",
    unionOrder: 50,
    unionDate: "August 21, 1959",
    region: "Pacific",
    areaSqMiles: "10,932 sq mi",
    pronunciation: "huh-WY-ee",
    funFacts: [
      "Hawaii is the only US state made entirely of islands — it has 137 islands in total.",
      "Hawaii's Mauna Kea volcano is the tallest mountain on Earth when measured from its oceanic base — over 33,000 feet.",
      "Hawaii is the only US state that grows coffee commercially and is famous for its Kona coffee.",
    ],
    stateBird: "Nene (Hawaiian Goose)",
    stateFlower: "Pua Aloalo (Yellow Hibiscus)",
    stateMotto: "Ua Mau ke Ea o ka Aina i ka Pono (The life of the land is perpetuated in righteousness)",
    fipsCode: "15",
    centerLon: -157.0,
    centerLat: 20.9,
    difficulty: 1,
  },
  {
    id: "idaho",
    name: "Idaho",
    abbreviation: "ID",
    capital: "Boise",
    capitalPop: "~235,000",
    unionOrder: 43,
    unionDate: "July 3, 1890",
    region: "Mountain West",
    areaSqMiles: "83,569 sq mi",
    pronunciation: "EYE-duh-hoh",
    funFacts: [
      "Idaho produces about one-third of all potatoes grown in the United States.",
      "Shoshone Falls in Idaho is taller than Niagara Falls, dropping 212 feet.",
      "Idaho has more whitewater river miles than any other contiguous US state.",
    ],
    stateBird: "Mountain Bluebird",
    stateFlower: "Syringa (Mock Orange)",
    stateMotto: "Esto Perpetua (Let it be perpetual)",
    fipsCode: "16",
    centerLon: -114.5,
    centerLat: 44.3,
    difficulty: 5,
  },
  {
    id: "illinois",
    name: "Illinois",
    abbreviation: "IL",
    capital: "Springfield",
    capitalPop: "~114,000",
    unionOrder: 21,
    unionDate: "December 3, 1818",
    region: "Midwest",
    areaSqMiles: "57,914 sq mi",
    pronunciation: "il-ih-NOY",
    funFacts: [
      "Illinois is known as the 'Land of Lincoln' — Abraham Lincoln spent most of his adult life there before becoming president.",
      "Chicago, Illinois, was home to the world's first skyscraper, built in 1885.",
      "Illinois has 102 counties and is a top producer of soybeans and corn in the US.",
    ],
    stateBird: "Northern Cardinal",
    stateFlower: "Violet",
    stateMotto: "State Sovereignty, National Union",
    fipsCode: "17",
    centerLon: -89.2,
    centerLat: 40.0,
    difficulty: 1,
  },
  {
    id: "indiana",
    name: "Indiana",
    abbreviation: "IN",
    capital: "Indianapolis",
    capitalPop: "~887,000",
    unionOrder: 19,
    unionDate: "December 11, 1816",
    region: "Midwest",
    areaSqMiles: "36,420 sq mi",
    pronunciation: "in-dee-AN-uh",
    funFacts: [
      "Indiana is nicknamed the 'Crossroads of America' because more interstate highways intersect there than in any other state.",
      "The Indianapolis 500, one of the world's oldest auto races, has been held every year since 1911.",
      "Indiana is the world's largest producer of popcorn.",
    ],
    stateBird: "Northern Cardinal",
    stateFlower: "Peony",
    stateMotto: "The Crossroads of America",
    fipsCode: "18",
    centerLon: -86.1,
    centerLat: 39.8,
    difficulty: 3,
  },
  {
    id: "iowa",
    name: "Iowa",
    abbreviation: "IA",
    capital: "Des Moines",
    capitalPop: "~214,000",
    unionOrder: 29,
    unionDate: "December 28, 1846",
    region: "Midwest",
    areaSqMiles: "56,273 sq mi",
    pronunciation: "EYE-oh-wuh",
    funFacts: [
      "Iowa produces about 16% of the nation's corn supply and is one of the top pork producers in the US.",
      "Iowa is the only state whose east and west borders are almost entirely formed by rivers.",
      "Iowa holds the nation's first presidential caucuses every four years, making it hugely influential in elections.",
    ],
    stateBird: "Eastern Goldfinch",
    stateFlower: "Wild Prairie Rose",
    stateMotto: "Our Liberties We Prize and Our Rights We Will Maintain",
    fipsCode: "19",
    centerLon: -93.5,
    centerLat: 42.0,
    difficulty: 4,
  },
  {
    id: "kansas",
    name: "Kansas",
    abbreviation: "KS",
    capital: "Topeka",
    capitalPop: "~125,000",
    unionOrder: 34,
    unionDate: "January 29, 1861",
    region: "Midwest",
    areaSqMiles: "82,278 sq mi",
    pronunciation: "KAN-zus",
    funFacts: [
      "Kansas is located in the geographic center of the continental United States.",
      "Kansas is the top wheat-producing state in the US, earning it the nickname 'The Wheat State.'",
      "The world's largest ball of twine — over 17,000 pounds — can be found in Cawker City, Kansas.",
    ],
    stateBird: "Western Meadowlark",
    stateFlower: "Sunflower",
    stateMotto: "Ad Astra per Aspera (To the Stars Through Difficulties)",
    fipsCode: "20",
    centerLon: -98.4,
    centerLat: 38.7,
    difficulty: 5,
  },
  {
    id: "kentucky",
    name: "Kentucky",
    abbreviation: "KY",
    capital: "Frankfort",
    capitalPop: "~28,000",
    unionOrder: 15,
    unionDate: "June 1, 1792",
    region: "Southeast",
    areaSqMiles: "40,408 sq mi",
    pronunciation: "ken-TUK-ee",
    funFacts: [
      "Kentucky is home to the world's longest known cave system — Mammoth Cave — with over 400 mapped miles.",
      "The Kentucky Derby, held annually in Louisville, is the oldest continuously run horse race in the US.",
      "Kentucky produces 95% of the world's bourbon whiskey.",
    ],
    stateBird: "Kentucky Cardinal",
    stateFlower: "Goldenrod",
    stateMotto: "United We Stand, Divided We Fall",
    fipsCode: "21",
    centerLon: -84.3,
    centerLat: 37.5,
    difficulty: 3,
  },
  {
    id: "louisiana",
    name: "Louisiana",
    abbreviation: "LA",
    capital: "Baton Rouge",
    capitalPop: "~225,000",
    unionOrder: 18,
    unionDate: "April 30, 1812",
    region: "South",
    areaSqMiles: "52,378 sq mi",
    pronunciation: "loo-EE-zee-an-uh",
    funFacts: [
      "Louisiana is the only US state whose legal system is based on French and Spanish civil law rather than English common law.",
      "New Orleans' Mardi Gras celebration is one of the largest festivals in North America.",
      "Louisiana has more miles of navigable waterways than any other US state.",
    ],
    stateBird: "Brown Pelican",
    stateFlower: "Magnolia",
    stateMotto: "Union, Justice, and Confidence",
    fipsCode: "22",
    centerLon: -91.8,
    centerLat: 31.0,
    difficulty: 3,
  },
  {
    id: "maine",
    name: "Maine",
    abbreviation: "ME",
    capital: "Augusta",
    capitalPop: "~19,000",
    unionOrder: 23,
    unionDate: "March 15, 1820",
    region: "Northeast",
    areaSqMiles: "35,380 sq mi",
    pronunciation: "MAYN",
    funFacts: [
      "Maine is the only US state that borders exactly one other state — New Hampshire.",
      "Maine produces 99% of all commercially harvested blueberries in the United States.",
      "Portland, Maine, has more restaurants per capita than any other city in the US.",
    ],
    stateBird: "Black-Capped Chickadee",
    stateFlower: "White Pine Cone and Tassel",
    stateMotto: "Dirigo (I Lead)",
    fipsCode: "23",
    centerLon: -69.2,
    centerLat: 45.4,
    difficulty: 4,
  },
  {
    id: "maryland",
    name: "Maryland",
    abbreviation: "MD",
    capital: "Annapolis",
    capitalPop: "~40,000",
    unionOrder: 7,
    unionDate: "April 28, 1788",
    region: "Northeast",
    areaSqMiles: "12,407 sq mi",
    pronunciation: "MAIR-ih-land",
    funFacts: [
      "Maryland is home to the US Naval Academy, founded in 1845 in Annapolis.",
      "The Maryland Blue Crab is famous worldwide — Maryland harvests millions of pounds annually from the Chesapeake Bay.",
      "Maryland was the first state to establish a state income tax, back in 1733.",
    ],
    stateBird: "Baltimore Oriole",
    stateFlower: "Black-Eyed Susan",
    stateMotto: "Fatti Maschii, Parole Femine (Strong Deeds, Gentle Words)",
    fipsCode: "24",
    centerLon: -76.9,
    centerLat: 39.0,
    difficulty: 2,
  },
  {
    id: "massachusetts",
    name: "Massachusetts",
    abbreviation: "MA",
    capital: "Boston",
    capitalPop: "~675,000",
    unionOrder: 6,
    unionDate: "February 6, 1788",
    region: "Northeast",
    areaSqMiles: "10,554 sq mi",
    pronunciation: "mas-uh-CHOO-sits",
    funFacts: [
      "Massachusetts is home to Harvard University, the oldest university in the United States, founded in 1636.",
      "The first American public school was established in Boston, Massachusetts, in 1635.",
      "Basketball was invented in Springfield, Massachusetts, in 1891 by Dr. James Naismith.",
    ],
    stateBird: "Black-Capped Chickadee",
    stateFlower: "Mayflower (Trailing Arbutus)",
    stateMotto: "Ense Petit Placidam Sub Libertate Quietem (By the Sword We Seek Peace, but Peace Only Under Liberty)",
    fipsCode: "25",
    centerLon: -71.5,
    centerLat: 42.2,
    difficulty: 2,
  },
  {
    id: "michigan",
    name: "Michigan",
    abbreviation: "MI",
    capital: "Lansing",
    capitalPop: "~112,000",
    unionOrder: 26,
    unionDate: "January 26, 1837",
    region: "Midwest",
    areaSqMiles: "96,714 sq mi",
    pronunciation: "MISH-ih-gun",
    funFacts: [
      "Michigan is the only state consisting of two separate peninsulas and is surrounded by four of the five Great Lakes.",
      "Detroit, Michigan, is the birthplace of the American automotive industry.",
      "Michigan has more than 11,000 inland lakes and 3,000 miles of freshwater coastline.",
    ],
    stateBird: "American Robin",
    stateFlower: "Apple Blossom",
    stateMotto: "Si Quaeris Peninsulam Amoenam Circumspice (If You Seek a Pleasant Peninsula, Look About You)",
    fipsCode: "26",
    centerLon: -85.5,
    centerLat: 44.3,
    difficulty: 2,
  },
  {
    id: "minnesota",
    name: "Minnesota",
    abbreviation: "MN",
    capital: "Saint Paul",
    capitalPop: "~311,000",
    unionOrder: 32,
    unionDate: "May 11, 1858",
    region: "Midwest",
    areaSqMiles: "86,936 sq mi",
    pronunciation: "min-ih-SOH-tuh",
    funFacts: [
      "Minnesota has more than 10,000 lakes — it's nicknamed 'The Land of 10,000 Lakes.'",
      "Minnesota is home to the headwaters of the Mississippi River, the longest river in North America.",
      "The Mall of America in Bloomington, Minnesota, is the largest mall in the US with over 520 stores.",
    ],
    stateBird: "Common Loon",
    stateFlower: "Pink and White Lady's Slipper",
    stateMotto: "L'Étoile du Nord (The Star of the North)",
    fipsCode: "27",
    centerLon: -94.3,
    centerLat: 46.3,
    difficulty: 3,
  },
  {
    id: "mississippi",
    name: "Mississippi",
    abbreviation: "MS",
    capital: "Jackson",
    capitalPop: "~153,000",
    unionOrder: 20,
    unionDate: "December 10, 1817",
    region: "Southeast",
    areaSqMiles: "48,432 sq mi",
    pronunciation: "mis-ih-SIP-ee",
    funFacts: [
      "Mississippi is the birthplace of the Blues music genre, which originated in the Mississippi Delta in the late 1800s.",
      "The Mississippi River, which borders the state, is the second longest river in North America.",
      "Mississippi is the leading producer of farm-raised catfish in the United States.",
    ],
    stateBird: "Mockingbird",
    stateFlower: "Magnolia",
    stateMotto: "Virtute et Armis (By Valor and Arms)",
    fipsCode: "28",
    centerLon: -89.7,
    centerLat: 32.7,
    difficulty: 4,
  },
  {
    id: "missouri",
    name: "Missouri",
    abbreviation: "MO",
    capital: "Jefferson City",
    capitalPop: "~43,000",
    unionOrder: 24,
    unionDate: "August 10, 1821",
    region: "Midwest",
    areaSqMiles: "69,707 sq mi",
    pronunciation: "muh-ZUR-ee",
    funFacts: [
      "Missouri is called the 'Gateway to the West' — the iconic Gateway Arch in St. Louis is the world's tallest arch at 630 feet.",
      "Missouri is one of only two US states to have two cities among the top 20 nationally — Kansas City and St. Louis.",
      "The ice cream cone was invented at the 1904 World's Fair in St. Louis, Missouri.",
    ],
    stateBird: "Eastern Bluebird",
    stateFlower: "White Hawthorn Blossom",
    stateMotto: "Salus Populi Suprema Lex Esto (The Welfare of the People Shall Be the Supreme Law)",
    fipsCode: "29",
    centerLon: -92.5,
    centerLat: 38.3,
    difficulty: 3,
  },
  {
    id: "montana",
    name: "Montana",
    abbreviation: "MT",
    capital: "Helena",
    capitalPop: "~33,000",
    unionOrder: 41,
    unionDate: "November 8, 1889",
    region: "Mountain West",
    areaSqMiles: "147,040 sq mi",
    pronunciation: "mon-TAN-uh",
    funFacts: [
      "Montana is the fourth largest US state by area and has more cattle than people.",
      "Glacier National Park in Montana has over 700 lakes and more than 200 species of birds.",
      "Montana has the longest undammed river in the contiguous US — the Yellowstone River.",
    ],
    stateBird: "Western Meadowlark",
    stateFlower: "Bitterroot",
    stateMotto: "Oro y Plata (Gold and Silver)",
    fipsCode: "30",
    centerLon: -110.4,
    centerLat: 46.9,
    difficulty: 4,
  },
  {
    id: "nebraska",
    name: "Nebraska",
    abbreviation: "NE",
    capital: "Lincoln",
    capitalPop: "~295,000",
    unionOrder: 37,
    unionDate: "March 1, 1867",
    region: "Midwest",
    areaSqMiles: "77,358 sq mi",
    pronunciation: "nuh-BRAS-kuh",
    funFacts: [
      "Nebraska is the only US state with a unicameral (one-chamber) legislature.",
      "Nebraska has more miles of river than any other state.",
      "Arbor Day was founded in Nebraska City, Nebraska, in 1872 by J. Sterling Morton.",
    ],
    stateBird: "Western Meadowlark",
    stateFlower: "Goldenrod",
    stateMotto: "Equality Before the Law",
    fipsCode: "31",
    centerLon: -100.0,
    centerLat: 41.5,
    difficulty: 5,
  },
  {
    id: "nevada",
    name: "Nevada",
    abbreviation: "NV",
    capital: "Carson City",
    capitalPop: "~58,000",
    unionOrder: 36,
    unionDate: "October 31, 1864",
    region: "Mountain West",
    areaSqMiles: "110,572 sq mi",
    pronunciation: "nuh-VAD-uh",
    funFacts: [
      "Nevada is the driest state in the US — most of it is desert or semi-arid.",
      "Las Vegas, Nevada, has more hotel rooms than any other city in the world.",
      "Nevada is the largest gold-producing state in the US and one of the top producers in the world.",
    ],
    stateBird: "Mountain Bluebird",
    stateFlower: "Sagebrush",
    stateMotto: "Battle Born",
    fipsCode: "32",
    centerLon: -116.8,
    centerLat: 39.3,
    difficulty: 3,
  },
  {
    id: "new-hampshire",
    name: "New Hampshire",
    abbreviation: "NH",
    capital: "Concord",
    capitalPop: "~44,000",
    unionOrder: 9,
    unionDate: "June 21, 1788",
    region: "Northeast",
    areaSqMiles: "9,349 sq mi",
    pronunciation: "noo HAMP-shur",
    funFacts: [
      "New Hampshire holds the first presidential primary election every four years, giving it outsized political influence.",
      "The highest wind speed ever recorded on Earth's surface — 231 mph — was measured atop Mount Washington in 1934.",
      "New Hampshire is the only state with no general sales tax and no income tax on wages.",
    ],
    stateBird: "Purple Finch",
    stateFlower: "Purple Lilac",
    stateMotto: "Live Free or Die",
    fipsCode: "33",
    centerLon: -71.6,
    centerLat: 43.7,
    difficulty: 5,
  },
  {
    id: "new-jersey",
    name: "New Jersey",
    abbreviation: "NJ",
    capital: "Trenton",
    capitalPop: "~91,000",
    unionOrder: 3,
    unionDate: "December 18, 1787",
    region: "Northeast",
    areaSqMiles: "8,723 sq mi",
    pronunciation: "noo JUR-zee",
    funFacts: [
      "New Jersey is the most densely populated state in the US.",
      "Thomas Edison invented the phonograph and the practical incandescent light bulb in Menlo Park, New Jersey.",
      "New Jersey is the nation's leading blueberry producer and is known as the 'Garden State' for its abundant farmland.",
    ],
    stateBird: "Eastern Goldfinch",
    stateFlower: "Common Blue Violet",
    stateMotto: "Liberty and Prosperity",
    fipsCode: "34",
    centerLon: -74.5,
    centerLat: 40.0,
    difficulty: 2,
  },
  {
    id: "new-mexico",
    name: "New Mexico",
    abbreviation: "NM",
    capital: "Santa Fe",
    capitalPop: "~84,000",
    unionOrder: 47,
    unionDate: "January 6, 1912",
    region: "Southwest",
    areaSqMiles: "121,590 sq mi",
    pronunciation: "noo MEK-sih-koh",
    funFacts: [
      "Santa Fe, New Mexico, is the highest US state capital at 7,000 feet and the oldest US state capital, founded in 1610.",
      "New Mexico has more PhD scientists and engineers per capita than any other state.",
      "White Sands National Park in New Mexico has the world's largest gypsum dune field.",
    ],
    stateBird: "Greater Roadrunner",
    stateFlower: "Yucca Flower",
    stateMotto: "Crescit Eundo (It Grows as It Goes)",
    fipsCode: "35",
    centerLon: -106.2,
    centerLat: 34.3,
    difficulty: 4,
  },
  {
    id: "new-york",
    name: "New York",
    abbreviation: "NY",
    capital: "Albany",
    capitalPop: "~99,000",
    unionOrder: 11,
    unionDate: "July 26, 1788",
    region: "Northeast",
    areaSqMiles: "54,555 sq mi",
    pronunciation: "noo YORK",
    funFacts: [
      "New York City, the largest city in the US, has a population of over 8 million and is home to the United Nations headquarters.",
      "New York was the first US state to require license plates on automobiles, in 1901.",
      "Niagara Falls, on the border with Canada, is one of the most visited natural wonders in the world.",
    ],
    stateBird: "Eastern Bluebird",
    stateFlower: "Rose",
    stateMotto: "Excelsior (Ever Upward)",
    fipsCode: "36",
    centerLon: -76.0,
    centerLat: 43.0,
    difficulty: 1,
  },
  {
    id: "north-carolina",
    name: "North Carolina",
    abbreviation: "NC",
    capital: "Raleigh",
    capitalPop: "~467,000",
    unionOrder: 12,
    unionDate: "November 21, 1789",
    region: "Southeast",
    areaSqMiles: "53,819 sq mi",
    pronunciation: "north kair-uh-LY-nuh",
    funFacts: [
      "The Wright Brothers made the world's first successful powered airplane flight at Kitty Hawk, North Carolina, in 1903.",
      "North Carolina is the nation's leading producer of sweet potatoes.",
      "The Great Smoky Mountains National Park, straddling the NC/TN border, is the most visited national park in the US.",
    ],
    stateBird: "Northern Cardinal",
    stateFlower: "Dogwood",
    stateMotto: "Esse Quam Videri (To Be Rather Than to Seem)",
    fipsCode: "37",
    centerLon: -79.4,
    centerLat: 35.6,
    difficulty: 2,
  },
  {
    id: "north-dakota",
    name: "North Dakota",
    abbreviation: "ND",
    capital: "Bismarck",
    capitalPop: "~73,000",
    unionOrder: 39,
    unionDate: "November 2, 1889",
    region: "Midwest",
    areaSqMiles: "70,698 sq mi",
    pronunciation: "north duh-KOH-tuh",
    funFacts: [
      "North Dakota is the least visited of all 50 states, yet it's one of the top energy-producing states.",
      "North Dakota leads the nation in production of sunflowers, canola, and flaxseed.",
      "The Geographic Center of North America is located near Rugby, North Dakota.",
    ],
    stateBird: "Western Meadowlark",
    stateFlower: "Wild Prairie Rose",
    stateMotto: "Liberty and Union, Now and Forever, One and Inseparable",
    fipsCode: "38",
    centerLon: -100.3,
    centerLat: 47.5,
    difficulty: 5,
  },
  {
    id: "ohio",
    name: "Ohio",
    abbreviation: "OH",
    capital: "Columbus",
    capitalPop: "~905,000",
    unionOrder: 17,
    unionDate: "March 1, 1803",
    region: "Midwest",
    areaSqMiles: "44,826 sq mi",
    pronunciation: "oh-HY-oh",
    funFacts: [
      "Ohio has produced more US presidents than any other state — seven presidents were born there.",
      "The first professional baseball team, the Cincinnati Red Stockings, was formed in Ohio in 1869.",
      "Ohio is a top manufacturer of plastics, rubber products, and fabricated metal goods.",
    ],
    stateBird: "Northern Cardinal",
    stateFlower: "Scarlet Carnation",
    stateMotto: "With God, All Things Are Possible",
    fipsCode: "39",
    centerLon: -82.8,
    centerLat: 40.4,
    difficulty: 1,
  },
  {
    id: "oklahoma",
    name: "Oklahoma",
    abbreviation: "OK",
    capital: "Oklahoma City",
    capitalPop: "~681,000",
    unionOrder: 46,
    unionDate: "November 16, 1907",
    region: "South",
    areaSqMiles: "69,899 sq mi",
    pronunciation: "oh-kluh-HOH-muh",
    funFacts: [
      "Oklahoma has more man-made lakes than any other state — over 200 reservoirs.",
      "Oklahoma is one of the most tornado-prone states in the US, sitting in 'Tornado Alley.'",
      "Oklahoma has the largest Native American population of any US state.",
    ],
    stateBird: "Scissor-Tailed Flycatcher",
    stateFlower: "Mistletoe",
    stateMotto: "Labor Omnia Vincit (Labor Conquers All Things)",
    fipsCode: "40",
    centerLon: -97.5,
    centerLat: 35.5,
    difficulty: 4,
  },
  {
    id: "oregon",
    name: "Oregon",
    abbreviation: "OR",
    capital: "Salem",
    capitalPop: "~175,000",
    unionOrder: 33,
    unionDate: "February 14, 1859",
    region: "Pacific",
    areaSqMiles: "98,379 sq mi",
    pronunciation: "OR-ih-gun",
    funFacts: [
      "Crater Lake in Oregon is the deepest lake in the United States at 1,943 feet deep.",
      "Oregon has the only state flag in the US with different images on each side — a beaver on the back.",
      "Oregon's Timberline Lodge on Mount Hood was used as the exterior of the Overlook Hotel in The Shining.",
    ],
    stateBird: "Western Meadowlark",
    stateFlower: "Oregon Grape",
    stateMotto: "She Flies With Her Own Wings",
    fipsCode: "41",
    centerLon: -120.5,
    centerLat: 44.0,
    difficulty: 2,
  },
  {
    id: "pennsylvania",
    name: "Pennsylvania",
    abbreviation: "PA",
    capital: "Harrisburg",
    capitalPop: "~50,000",
    unionOrder: 2,
    unionDate: "December 12, 1787",
    region: "Northeast",
    areaSqMiles: "46,054 sq mi",
    pronunciation: "pen-sil-VAYN-yuh",
    funFacts: [
      "Pennsylvania's Independence Hall in Philadelphia is where both the Declaration of Independence and the US Constitution were signed.",
      "The first commercially drilled oil well in the US was drilled in Titusville, Pennsylvania, in 1859.",
      "Hershey, Pennsylvania, is home to the world's largest chocolate manufacturer and an amusement park called Hersheypark.",
    ],
    stateBird: "Ruffed Grouse",
    stateFlower: "Mountain Laurel",
    stateMotto: "Virtue, Liberty, and Independence",
    fipsCode: "42",
    centerLon: -77.2,
    centerLat: 41.0,
    difficulty: 1,
  },
  {
    id: "rhode-island",
    name: "Rhode Island",
    abbreviation: "RI",
    capital: "Providence",
    capitalPop: "~190,000",
    unionOrder: 13,
    unionDate: "May 29, 1790",
    region: "Northeast",
    areaSqMiles: "1,545 sq mi",
    pronunciation: "rohd EYE-land",
    funFacts: [
      "Rhode Island is the smallest US state by area yet has the longest official name: 'State of Rhode Island and Providence Plantations.'",
      "Rhode Island was the first state to declare independence from Britain on May 4, 1776.",
      "Newport, Rhode Island, hosts the oldest jazz festival in the world — the Newport Jazz Festival, started in 1954.",
    ],
    stateBird: "Rhode Island Red",
    stateFlower: "Violet",
    stateMotto: "Hope",
    fipsCode: "44",
    centerLon: -71.5,
    centerLat: 41.6,
    difficulty: 5,
  },
  {
    id: "south-carolina",
    name: "South Carolina",
    abbreviation: "SC",
    capital: "Columbia",
    capitalPop: "~136,000",
    unionOrder: 8,
    unionDate: "May 23, 1788",
    region: "Southeast",
    areaSqMiles: "32,020 sq mi",
    pronunciation: "south kair-uh-LY-nuh",
    funFacts: [
      "South Carolina was the first state to secede from the Union in 1860, triggering the Civil War.",
      "South Carolina grows more peaches than Georgia — earning it a competing nickname, the 'Tastier Peach State.'",
      "Fort Sumter in Charleston Harbor is where the first shots of the Civil War were fired on April 12, 1861.",
    ],
    stateBird: "Carolina Wren",
    stateFlower: "Yellow Jessamine",
    stateMotto: "Dum Spiro Spero (While I Breathe, I Hope)",
    fipsCode: "45",
    centerLon: -81.0,
    centerLat: 34.0,
    difficulty: 3,
  },
  {
    id: "south-dakota",
    name: "South Dakota",
    abbreviation: "SD",
    capital: "Pierre",
    capitalPop: "~14,000",
    unionOrder: 40,
    unionDate: "November 2, 1889",
    region: "Midwest",
    areaSqMiles: "77,116 sq mi",
    pronunciation: "south duh-KOH-tuh",
    funFacts: [
      "Mount Rushmore in South Dakota features 60-foot carvings of Presidents Washington, Jefferson, Roosevelt, and Lincoln.",
      "The Black Hills of South Dakota contain some of the world's oldest rocks, dating back nearly 2 billion years.",
      "Custer State Park in South Dakota has one of the largest free-roaming bison herds in the world.",
    ],
    stateBird: "Ring-Necked Pheasant",
    stateFlower: "Pasque Flower",
    stateMotto: "Under God the People Rule",
    fipsCode: "46",
    centerLon: -100.2,
    centerLat: 44.4,
    difficulty: 5,
  },
  {
    id: "tennessee",
    name: "Tennessee",
    abbreviation: "TN",
    capital: "Nashville",
    capitalPop: "~689,000",
    unionOrder: 16,
    unionDate: "June 1, 1796",
    region: "Southeast",
    areaSqMiles: "42,144 sq mi",
    pronunciation: "ten-ih-SEE",
    funFacts: [
      "Tennessee is the birthplace of country music — Nashville's 'Music Row' is the heart of the industry.",
      "Tennessee borders eight other states — more than any other US state.",
      "Graceland, Elvis Presley's home in Memphis, is the second most visited house in the US after the White House.",
    ],
    stateBird: "Mockingbird",
    stateFlower: "Iris",
    stateMotto: "Agriculture and Commerce",
    fipsCode: "47",
    centerLon: -86.7,
    centerLat: 35.9,
    difficulty: 3,
  },
  {
    id: "texas",
    name: "Texas",
    abbreviation: "TX",
    capital: "Austin",
    capitalPop: "~978,000",
    unionOrder: 28,
    unionDate: "December 29, 1845",
    region: "South",
    areaSqMiles: "268,596 sq mi",
    pronunciation: "TEK-sus",
    funFacts: [
      "Texas is the second largest US state by area and population and was an independent republic from 1836 to 1845.",
      "Texas produces more oil than any other US state and is home to the most Fortune 500 companies.",
      "The King Ranch in Texas is larger than Rhode Island, covering about 825,000 acres.",
    ],
    stateBird: "Mockingbird",
    stateFlower: "Bluebonnet",
    stateMotto: "Friendship",
    fipsCode: "48",
    centerLon: -99.0,
    centerLat: 31.5,
    difficulty: 1,
  },
  {
    id: "utah",
    name: "Utah",
    abbreviation: "UT",
    capital: "Salt Lake City",
    capitalPop: "~200,000",
    unionOrder: 45,
    unionDate: "January 4, 1896",
    region: "Mountain West",
    areaSqMiles: "84,897 sq mi",
    pronunciation: "YOO-taw",
    funFacts: [
      "Utah has five national parks — Arches, Bryce Canyon, Canyonlands, Capitol Reef, and Zion — more than any neighboring state.",
      "The Great Salt Lake is the largest saltwater lake in the Western Hemisphere.",
      "Utah was the site of the completion of the first transcontinental railroad at Promontory Summit in 1869.",
    ],
    stateBird: "California Gull",
    stateFlower: "Sego Lily",
    stateMotto: "Industry",
    fipsCode: "49",
    centerLon: -111.1,
    centerLat: 39.5,
    difficulty: 4,
  },
  {
    id: "vermont",
    name: "Vermont",
    abbreviation: "VT",
    capital: "Montpelier",
    capitalPop: "~8,000",
    unionOrder: 14,
    unionDate: "March 4, 1791",
    region: "Northeast",
    areaSqMiles: "9,616 sq mi",
    pronunciation: "ver-MONT",
    funFacts: [
      "Vermont is the smallest state in New England and the second least populated state in the US.",
      "Vermont produces more maple syrup per capita than any other US state — about 40% of the national supply.",
      "Vermont was the first state to abolish slavery, in 1777, before it even joined the union.",
    ],
    stateBird: "Hermit Thrush",
    stateFlower: "Red Clover",
    stateMotto: "Freedom and Unity",
    fipsCode: "50",
    centerLon: -72.8,
    centerLat: 44.3,
    difficulty: 5,
  },
  {
    id: "virginia",
    name: "Virginia",
    abbreviation: "VA",
    capital: "Richmond",
    capitalPop: "~226,000",
    unionOrder: 10,
    unionDate: "June 25, 1788",
    region: "Southeast",
    areaSqMiles: "42,775 sq mi",
    pronunciation: "ver-JIN-yuh",
    funFacts: [
      "Virginia is nicknamed the 'Mother of Presidents' — eight US presidents were born there, more than any other state.",
      "Jamestown, Virginia, founded in 1607, was the first permanent English settlement in North America.",
      "The Pentagon, the world's largest office building, is located in Arlington, Virginia.",
    ],
    stateBird: "Northern Cardinal",
    stateFlower: "American Dogwood",
    stateMotto: "Sic Semper Tyrannis (Thus Always to Tyrants)",
    fipsCode: "51",
    centerLon: -78.5,
    centerLat: 37.5,
    difficulty: 2,
  },
  {
    id: "washington",
    name: "Washington",
    abbreviation: "WA",
    capital: "Olympia",
    capitalPop: "~55,000",
    unionOrder: 42,
    unionDate: "November 11, 1889",
    region: "Pacific",
    areaSqMiles: "71,298 sq mi",
    pronunciation: "WOSH-ing-ton",
    funFacts: [
      "Washington is the only US state named after a president.",
      "Washington produces more apples than any other US state — nearly 60% of all apples grown in the nation.",
      "Mount Rainier in Washington is the most heavily glaciated peak in the contiguous United States.",
    ],
    stateBird: "Willow Goldfinch",
    stateFlower: "Coast Rhododendron",
    stateMotto: "Al-ki (Bye and Bye)",
    fipsCode: "53",
    centerLon: -120.5,
    centerLat: 47.5,
    difficulty: 2,
  },
  {
    id: "west-virginia",
    name: "West Virginia",
    abbreviation: "WV",
    capital: "Charleston",
    capitalPop: "~49,000",
    unionOrder: 35,
    unionDate: "June 20, 1863",
    region: "Southeast",
    areaSqMiles: "24,230 sq mi",
    pronunciation: "west ver-JIN-yuh",
    funFacts: [
      "West Virginia is the only state formed by seceding from another state — it broke off from Virginia during the Civil War.",
      "West Virginia has the lowest mean elevation of any state east of the Mississippi and the most varied terrain.",
      "New River Gorge in West Virginia has the world's longest single-span steel arch bridge.",
    ],
    stateBird: "Northern Cardinal",
    stateFlower: "Rhododendron",
    stateMotto: "Montani Semper Liberi (Mountaineers Are Always Free)",
    fipsCode: "54",
    centerLon: -80.5,
    centerLat: 38.6,
    difficulty: 4,
  },
  {
    id: "wisconsin",
    name: "Wisconsin",
    abbreviation: "WI",
    capital: "Madison",
    capitalPop: "~269,000",
    unionOrder: 30,
    unionDate: "May 29, 1848",
    region: "Midwest",
    areaSqMiles: "65,496 sq mi",
    pronunciation: "wis-KON-sin",
    funFacts: [
      "Wisconsin produces more cheese than any other US state — about 25% of all US cheese.",
      "Wisconsin has about 15,000 lakes and is a leading dairy state, earning the nickname 'America's Dairyland.'",
      "The Republican Party was founded in Ripon, Wisconsin, in 1854.",
    ],
    stateBird: "American Robin",
    stateFlower: "Wood Violet",
    stateMotto: "Forward",
    fipsCode: "55",
    centerLon: -90.2,
    centerLat: 44.5,
    difficulty: 3,
  },
  {
    id: "wyoming",
    name: "Wyoming",
    abbreviation: "WY",
    capital: "Cheyenne",
    capitalPop: "~64,000",
    unionOrder: 44,
    unionDate: "July 10, 1890",
    region: "Mountain West",
    areaSqMiles: "97,813 sq mi",
    pronunciation: "wy-OH-ming",
    funFacts: [
      "Wyoming was the first US state to grant women the right to vote, in 1869.",
      "Yellowstone National Park, mostly in Wyoming, was the world's first national park, established in 1872.",
      "Wyoming is the least populous US state with fewer than 600,000 residents.",
    ],
    stateBird: "Western Meadowlark",
    stateFlower: "Indian Paintbrush",
    stateMotto: "Equal Rights",
    fipsCode: "56",
    centerLon: -107.6,
    centerLat: 43.0,
    difficulty: 5,
  },
];
